### ISSUE TITLE
DPL-803	Add library creation data to MLWH pac_bio_run table

### ISSUE THREAD

**Issue by neilsycamore** [sanger/traction-service#1039] opened 2023-06-28 15:20 UTC
As Kirsten H, Head of Production Genomics (ToL) we would like the mlwarehouse pacbio_run library_created_at field populated by Traction.
We would also like the data retrofitted for this field

**User story**
Having this in mlwh would be absolutely fantastic and solve many issues we’re currently facing of tracking our samples.

**Who are the primary contacts for this story**
kj2@

**Who is the nominated tester for UAT**
nts@

**Acceptance criteria**
To be considered successful the solution must allow:
- [1 ] on run creation library_created_at data should be added to the table
- [2] past runs should also have the library_created_at field populated

**Comment by neilsycamore** [comment] 2023-06-28 15:30
probably needs to be split into two stories?
Traction message update 
Data migration

**Comment by BenTopping** [comment] 2023-07-03 09:09
Sounds like we need to update the message to MLWH and then re-broadcast every plate. Wondering why we dont populate this currently, maybe it is a legacy field? @stevieing any thoughts?

**Comment by SujitDey2022** [comment] 2023-08-08 10:17
@BenTopping This was kept in the Triage column as @stevieing had mentioned he will discuss and move this to the relevant position on the board. As he is on leave please can you help identify the urgency and complexity of the changes in order to prioritise it better.

@TWJW-SANGER fyi...

**Comment by BenTopping** [comment] 2023-08-08 10:39
> @BenTopping This was kept in the Triage column as @stevieing had mentioned he will discuss and move this to the relevant position on the board. As he is on leave please can you help identify the urgency and complexity of the changes in order to prioritise it better.
> 
> @TWJW-SANGER fyi...

@SujitDey2022  I don't know the urgency because I was not involved in the story proposal or requirements gathering, but it sounds like they currently have a process and that this work would just be an improvement upon it. As for the complexity, it is probably a medium sized task. As mentioned in a previous comment I don't know why this field is not populated already and it may contain legacy data that we don't want to overwrite. Unfortunately I think @stevieing is the only one who can answer these questions.

**Comment by stevieing** [comment] 2024-08-20 12:53
Closed as duplicate of #859

**Closed by stevieing** 2024-08-20 12:53 UTC
Labels: Value: 4
